WITH RECURSIVE A AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT b.ID, a.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA b
    JOIN A a ON a.ID = b.PARENT_ID
)

SELECT ID
FROM A
WHERE GENERATION = 3