WITH RECURSIVE GENERATION AS (
  SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
   WHERE Parent_ID IS NULL
    
  UNION ALL

  SELECT p.ID, g.GENERATION + 1
    FROM ECOLI_DATA p
    JOIN GENERATION g ON p.PARENT_ID = g.ID
)

  SELECT COUNT(ID) AS COUNT, GENERATION
    FROM GENERATION g
   WHERE (SELECT Count(*) 
            FROM ECOLI_DATA aa
           WHERE g.ID = aa.Parent_ID
         ) = 0
GROUP BY GENERATION