WITH RECURSIVE A AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL

    SELECT b.ID, 1 + a.GENERATION AS GENERATION
    FROM ECOLI_DATA b
    JOIN A a ON a.ID = b.PARENT_ID
)

SELECT COUNT(ID) COUNT, GENERATION
FROM A c
WHERE (SELECT COUNT(ID) 
         FROM ECOLI_DATA d 
        WHERE d.PARENT_ID = c.ID) = 0
GROUP BY GENERATION