SELECT AA.ID, AA.GENOTYPE,
    (SELECT BB.GENOTYPE 
       FROM ECOLI_DATA AS BB 
      WHERE BB.ID = AA.PARENT_ID 
        AND BB.GENOTYPE & AA.GENOTYPE = BB.GENOTYPE
    ) AS PARENT_GENOTYPE
FROM ECOLI_DATA AS AA
INNER JOIN ECOLI_DATA AS CC ON CC.ID = AA.PARENT_ID AND CC.GENOTYPE & AA.GENOTYPE = CC.GENOTYPE
WHERE AA.PARENT_ID IS NOT NULL
ORDER BY ID