WITH FRONT AS (
    SELECT SUM(CODE) AS FRONTCODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
C AS (
    SELECT CODE AS CCODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
),
PYTHON AS (
    SELECT CODE AS PCODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
)

SELECT CASE 
           WHEN FRONT.FRONTCODE & SKILL_CODE > 0 AND PYTHON.PCODE & SKILL_CODE = PYTHON.PCODE THEN 'A'
           WHEN C.CCODE & SKILL_CODE = C.CCODE THEN 'B'
           WHEN FRONT.FRONTCODE & SKILL_CODE > 0 THEN 'C'
       END AS GRADE,
       ID, 
       EMAIL
FROM DEVELOPERS
INNER JOIN FRONT ON 1=1
INNER JOIN C ON 1=1
INNER JOIN PYTHON ON 1=1
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;
